### ISSUE TITLE
zarr data sets on disk get rechunked when adding a new unknown column 

### ISSUE THREAD

**Issue by landmanbester** [ratt-ru/QuartiCal#179] opened 2022-07-19 16:23 UTC
I created a zarr data set that is chunked along the row dimension using dask-ms
```
dask-ms convert ~/projects/ESO137/msdir/ms1_target_subset.ms -g "FIELD_ID,DATA_DESC_ID,SCAN_NUMBER" -i "TIME,ANTENNA1,ANTENNA2,FEED1,FEED2" -o "s3://pfb-bucket/ms1_target_subset.zarr" --chunks="{row:50000}" --format zarr --force
``` 
I then attempt to calibrate the data using QuartiCal and ask it write the residual to a column that doesn't exist in the data set. It falls over with
```
ValueError: Object has inconsistent chunks along dimension row. This can be fixed by calling unify_chunks().
```  
What's more, all data variables in the resulting data set end up getting rechunked along the row dimension with chunks equal to the chunks used to load the data. In this case, since I loaded the data with ```input_ms.time_chunk=4``` and I end up with row chunks of size 7564 (i.e. exactly 4 unique times per chunk). The full log is on janis /home/bester/projects/ESO137/ 20220719_152901.log.qc

**To Reproduce**
In principle it should reproduce by setting ```input_ms.time_chunk``` to a value that results in different chunks than on disk chunks and writing a result out to a column that doesn't yet exists in the data set. Reproducer to follow when I get a chance.

**Expected behavior**
The run should finish normally with the on disk chunks unaltered

**Version**
On the stimelation branch

**Comment by landmanbester** [comment] 2022-07-19 16:27
I should add that the data lives on s3 in this case

**Comment by JSKenyon** [comment] 2022-07-20 12:40
I have begun digging into this. It wasn't listed in the issue, but I have tracked down the reason why QuartiCal was adding attributes to the zarr stores - this is not a big deal and shouldn't be the cause of any problems. I have not yet managed to reproduce the rechunking case. I can reproduce the crash one experiences when writing a new column to zarr (with chunking that differs from the on disk chunking of already written data_vars). I will continue to investigate.

**Comment by landmanbester** [comment] 2022-07-20 13:40
Thanks. I was running this through a stimela recipe. Not sure if something else could have gone wrong in the process. I will also try to set up a reproducer

**Comment by JSKenyon** [comment] 2022-07-21 09:19
OK, there is now a PR on dask-ms which should fix the new column problem: https://github.com/ratt-ru/dask-ms/pull/236. 

Feel free to give it a go @landmanbester. I would be interested to see if you can reproduce the mysterious rechunking.

**Comment by landmanbester** [comment] 2022-07-25 09:03
I reran the exact same pipeline with the above branch and it ran through without the weird rechunking. I am not sure how I managed to get into that situation but the problem seems to be fixed now. Thanks @JSKenyon

**Comment by JSKenyon** [comment] 2022-07-25 09:11
Great @landmanbester. Let's keep an eye out for it, just in case it happens again. I will close this once https://github.com/ratt-ru/dask-ms/pull/236 is merged (or a variation of it).

**Comment by JSKenyon** [comment] 2022-10-18 14:01
Closing, but feel free to open @landmanbester if it happens again.

**Closed by JSKenyon** 2022-10-18 14:01 UTC
